expr: ???

hydra:
  run:
    dir: outputs/${expr}/${now:%Y-%m-%d-%H-%M-%S}

data_root: "/home/appuser/datasets"
model_root: "/home/appuser/models"

mode: "fit"

defaults:
  - datamodule:
    - imagenet
  - model: dino
  - trainer: default
