expr: ???
git_hash: ""

output_dir: /home/appuser/models
hydra:
  run:
    dir: ${output_dir}/${expr}

ckpt_path: ""
data_root: "/home/appuser/datasets"

defaults:
  - datamodule:
    - imagenet
  - model: dino
  - trainer: default
