version: "2.3"
services:
  dogifier:
    container_name: dogifier-${USER}
    image: dogifier:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        PROJECT_NAME: ${PROJECT_NAME:-project}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ../:/home/appuser/${PROJECT_NAME}
      - ~/datasets:/home/appuser/datasets
      - ~/models:/home/appuser/models
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
